///
//    TO DEFINE YOUR SELECTORE CORRECTLY OR IN CASE OF CONFUSION
//   AFTER YOU SETUP YOUR REDUCER YOU CHECK YOUR DEVTOOLS REDUX
// ON YOUR BROWSER
//  SO TO STATE AND THE THEN YOU CAN SELECT ALL THE STATE EASLY
// WITH CORRECT NAMING
///
export const selectAllExpenses = (reduxState) =>
  reduxState.expenses.allExpenses;
